import { Router } from 'express';
import * as clipController from '../controllers/clipController.js';
import { authenticate } from '../middleware/auth.js';
const router = Router();
router.get('/', authenticate, clipController.getClips);
router.get('/:id', authenticate, clipController.getClip);
router.post('/', authenticate, clipController.createClip);
router.put('/:id', authenticate, clipController.updateClip);
router.delete('/:id', authenticate, clipController.deleteClip);
export default router;
