import { Router } from 'express';
import * as postController from '../controllers/postController.js';
import { authenticate } from '../middleware/auth.js';
const router = Router();
router.get('/', authenticate, postController.getPosts);
router.get('/:id', authenticate, postController.getPost);
router.post('/', authenticate, postController.createPost);
router.put('/:id', authenticate, postController.updatePost);
router.delete('/:id', authenticate, postController.deletePost);
router.post('/:id/schedule', authenticate, postController.schedulePost);
router.post('/:id/publish', authenticate, postController.publishPost);
export default router;
