import { Router } from 'express';
import * as videoController from '../controllers/videoController.js';
import { authenticate } from '../middleware/auth.js';
const router = Router();
router.get('/', authenticate, videoController.getVideos);
router.get('/:id', authenticate, videoController.getVideo);
router.post('/', authenticate, videoController.createVideo);
router.put('/:id', authenticate, videoController.updateVideo);
router.delete('/:id', authenticate, videoController.deleteVideo);
router.post('/upload', authenticate, videoController.uploadVideo);
export default router;
